server:
  port: 8080

name: registration

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: yassarhammami@gmail.com
    password: mfalrrenjnufcvvo
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 20000

support:
  email: yassarhammami@gmail.com
